version: '2'
services:
# poxa:
#   image: edgurgel/poxa-automated:latest
#   ports:
#     - 8080:8080
#   volumes:
#     - ./poxa.conf:/app/poxa/releases/0.8.0/poxa.conf

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis:latest

  myapp:
    tty: true
    #image: 'bitnami/rails:latest'          # uncomment this to run from the local copy
    build:                                # uncomment this to use a built container
      context: .                          # uncomment this to use a built container
      dockerfile: docker/web/Dockerfile   # uncomment this to use a built container
    labels:
      kompose.service.type: nodeport
    depends_on:
      - mariadb
      - redis
    ports:
      - 3002:3000
    volumes:
      #- ./overt:/app                   # uncomment this to run from the local copy
      - ./overt/db:/app/db            # uncomment this to use a built container
      - ./tmp_web:/app/tmp
      - ./workflows:/workflows
    env_file:
      - .env

  sidekiq:
    tty: true
    #image: 'bitnami/rails:latest'          # uncomment this to run from the local copy
    build:                                    # uncomment this to use a built container
      context: .                              # uncomment this to use a built container
      dockerfile: docker/sidekiq/Dockerfile   # uncomment this to use a built container
    command: bundle exec sidekiq
    labels:
      kompose.service.type: nodeport
    depends_on:
      - mariadb
      - redis
    volumes:
      #- ./overt:/app                   # uncomment this to run from the local copy
      - ./overt/db:/app/db            # uncomment this to use a built container
      - ./tmp_sidekiq:/app/tmp
      - ./workflows:/workflows
    env_file:
      - .env
    environment:
      - SKIP_DB_SETUP=yes