version: '2'
services:
  poxa:
    image: edgurgel/poxa-automated:latest
    ports:
      - 8080:8080
    volumes:
      - ./poxa.conf:/app/poxa/releases/0.8.0/poxa.conf

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis:latest

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/rails:latest'
    labels:
      kompose.service.type: nodeport
    depends_on:
      - mariadb
      - redis
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - ./poxa.conf:/test/test.txt
      - ./workflows:/workflows
    env_file:
      - .env

#  sidekiq:
#    build: .
#    command: bundle exec sidekiq
#    depends_on:
#      - mariadb
#      - redis
#    volumes:
#      - .:/app
#    env_file:
#      - .env
